name: Fudge Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget bzip2

      - name: Download and Install crosstool-ng
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.bz2
          tar xjf crosstool-ng-1.26.0.tar.bz2
          cd crosstool-ng-1.26.0
          ./configure
          make
          sudo make install

      - name: Configure Cross-Compiler
        run: |
          mkdir ~/temp
          cd ~/temp
          ct-ng menuconfig
          # Manually configure the target architecture to x86 and save the configuration

      - name: Build Cross-Compiler
        run: |
          ct-ng build

      - name: Clone Fudge Repository
        run: git clone git://github.com/jezze/fudge.git

      - name: Set PATH for Cross-Compiler
        run: export PATH=/home/$(whoami)/x-tools/i386-unknown-elf/bin:$PATH

      - name: Build Fudge
        run: |
          cd fudge
          make

      - name: Run Fudge in QEMU
        run: |
          ./vmctrl runsimple node1

      - name: Test Fudge
        run: |
          # Add testing commands here
