name: CI/CD with i686-elf-gcc and i686-elf-g++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
    - name: Install make 
      run: brew install make

    - name: Install Nasm
      run: brew install nasm


    - name: Install i686-elf-gcc
      run: brew install i686-elf-gcc
    - name: Build project
      run: |
        brew install bchunk
        brew install qemu
        # nasm -f elf32 -O0 kernelz/src/core/cpuhelper.asm -o kernelz/obj/core/cpuhelper.o
        (make qemu) & pid=$! ; (sleep 10 && kill -9 $pid &)
