name: Fudge Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget bzip2 xz-utils unzip help2man libtool-bin nasm
      - name: Compile2Iso
        run: |
          make


      - name: Set PATH for Cross-Compiler
        run: export PATH=/home/$(whoami)/x-tools/i386-unknown-elf/bin:$PATH

      - name: Build BadBlueKernel
        run: |
          make


