name: BadBlueKernel-Build

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test Fudge OS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget make gcc git qemu-user-static help2man libtool-bin
      
      - name: Download and install crosstool-ng
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.26.0.tar.bz2
          tar xjf crosstool-ng-1.26.0.tar.bz2
          cd crosstool-ng-1.26.0
          ./configure
          make
          sudo make install
      
      - name: Install libtool
        run: |
          sudo apt-get install -y libtool
      
      - name: Create default configuration file
        run: |
          mkdir ~/temp
          cd ~/temp
          echo "CT_ARCH_x86=y" > .config
          echo "CT_TARGET_x86_64_unknown_linux_gnu=y" >> .config
          echo "CT_CC_GCC_LINARO=y" >> .config
          echo "CT_CC_LANG_CXX=y" >> .config
      
      - name: Configure cross-compiler
        run: |
          cd ~/temp
          ct-ng oldconfig
      
      - name: Build cross-compiler
        run: |
          ct-ng build
      
      - name: Clone Fudge OS repository
        run: |
          git clone git://github.com/jezze/fudge.git
          cd fudge
      
      - name: Set cross-compiler path
        run: |
          export PATH=/home/$(whoami)/x-tools/i386-unknown-elf/bin:$PATH
      
      - name: Build BadBlueKernel
        run: |
          make
